
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  gcp-secret-dev
  namespace: frontend
  

spec:
  refreshInterval: 10s         # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: gcp-frontend-secret           # name of the SecretStore (or kind specified)
  target:
    name:  frontend-secret # name of the k8s Secret to be created
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: FRONTEND_SECRETS
  
