
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-frontend-secret 
  namespace: frontend

    
spec:
  provider:
    gcpsm:
     
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: asia-south2-a
          # name of the GKE cluster
          clusterName: demo-eso
        
         
          # reference the sa from above
          serviceAccountRef:
            name: gcpsm-accessor 
